# Copia desde application-local.properties.example y rellena tus valores.
# Este archivo no se sube a Git.

spring.security.oauth2.client.registration.google.client-id=124461081154-m9blh99f20crl70t0urqqu7hf0961cad.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
