server.port=${PORT:8080}
spring.application.name=demo

# Thymeleaf
spring.thymeleaf.cache=false

# ✅ MongoDB
mongodb+srv://dalithg29_db_user:<db_password>@cultivus.jyejg6e.mongodb.net/

server.error.include-message=always
server.error.include-stacktrace=always

# ✅ Google OAuth2 — reemplaza los valores con los de Google Cloud Console
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:124461081154-m9blh99f20crl70t0urqqu7hf0961cad.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google